epochs: 100                # Max Number of epochs
early_stopping_epochs: 20   # Early stopping epochs
model: mve_pinn           # baseline, snn, pinn, mve_snn, mve_pinn
network: dcenet_unc         # fc, fc_unc, dcenet, dcenet_unc
mode: vivo                   # Model mode: sim or invivo
weights:                    # path to pretrained weights
dataset: vivo                # Train dataset: sim or invivo
batch_size: 256             # Batch size
lr: 1e-4                   # Learning rate
batch_per_epoch: 0.01        # Fraction of dataset to use per epoch
logger: wandb                   # wandb or None (for default local logging)
debug: 0                    # 0 or 1
mcd: 0                      # 0 or 1, only for snn and pinn        # 
kwargs: {
  burnin_epochs: 1, # Burnin epochs, only used for MVE models
  dt_predictor: True #output/normal/baselines/baseline_dcenet_0/best.ckpt
}