epochs: 200                 # Max Number of epochs
burnin_epochs: 3            # Burnin epochs, only used for MVE models
early_stopping_epochs: 20   # Early stopping epochs
model: snn                  # baseline, snn, pinn, mve_snn, mve_pinn
network: dcenet             # fc, fc_unc, dcenet, dcenet_unc
mode: sim                   # Model mode: sim or invivo
seed: 0                     # seed for reproducibility
weights:                    # path to pretrained weights
dataset: ood                # Train dataset: sim or invivo
batch_size: 256             # Batch size
lr: 1e-4                    # Learning rate
batch_per_epoch: 0.1        # Fraction of dataset to use per epoch
logger: wandb               # wandb or None (for default local logging)
debug: 0                    # 0 or 1
mcd: 0                      # 0 or 1, only for snn and pinn