seed: 0
paths: [
  "normal/mve_snn_dcenet_0",
  "normal/mve_snn_dcenet_1",
  "normal/mve_snn_dcenet_2",
  "normal/mve_snn_dcenet_3",
  "normal/mve_snn_dcenet_4",
]
logger:  
debug: False
dataset: normal