seed: 0
paths: [
  "normal/mve_pinn_dcenet_0",
  "normal/mve_pinn_dcenet_1",
  "normal/mve_pinn_dcenet_2",
  "normal/mve_pinn_dcenet_3",
  "normal/mve_pinn_dcenet_4",
]
logger: wandb
debug: False
dataset: normal